spring:
  datasource:
    url: jdbc:h2:mem:services;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-local.yml
logging:
  level:
    org.springframework.web: DEBUG
